# accessing env vars
BUCKET_NAME_ENV_VAR = "BUCKET_NAME"
ACCESS_KEY_ENV_VAR  = "ACCESS_KEY"
SECRET_KEY_ENV_VAR  = "SECRET_KEY"
OBJECT_URL_ENV_VAR  = "OBJECT_URL"
AWS_REGION_ENV_VAR  = "AWS_REGION"

# routes
UPLOAD_TO_S3_ROUTE = "/s3"
GET_FROM_S3_ROUTE  = "/s3"

UPLOAD_DELECT_LABELS = "/rekognition"

CUSTOM_TILE_ROUTE = '/custom-tile'

# error
S3_IMAGE_UPLOAD_FAILURE_MSG = "Image could not be uploaded to storage"

# Testing Data (if tests become ever possible)
SAMPLE_BASE64_IMAGE = "iVBORw0KGgoAAAANSUhEUgAAADIAAAAyCAYAAAAeP4ixAAAACXBIWXMAAAsTAAALEwEAmpwYAAACHElEQVR4nO2ZMUscQRiGHxM1EC3sTBGJIViIqGAXT/0B5oIJ+gcsYi8SLFQsFP9DuvT+BjVWIQp2SRVBIqgBNXBnI1FHxnyL47J7Nyt6+0nmhY+de2dm93uYnZndWwgKCrqt3gJrwAlgco4TYBUoZoVYUpC8SYnFLCNhlEfRB2RNQaKmSqz4gJQVJGqqRMkHpJYJ9QMDHp5JCFUgSdeMFEAi1eJ2yqIBrbdWISPIoFaQMEcII0KY7CZM9muFDTGP5beQsE8UKuwdaveRu9iDUpV3giaAxPTfjMgpsCfHBwnyCxgFGqRdIzAG7Hpc9MM9jHhVJXU6BNql3oI8c4BeAscVLrjscf6agUw5LzkH4u0Dr8X/mNJvB2jRBNIpdd9i/lfxuxL6/HVeot5rAWmUujPgCNgCfkuy08BcQp9Z6dMmfVSARHoH1EnZHodTJrv9k++xxHrsHCpArJqBPqDp6te/ReDQaWvLz6VuPuEcKkCGgD/iHcvDndWk03ZEvEG5FVWC/Ij538V/Ib8vnLYzwCcnItnyl7xA6oFHwHnMPxf/SQJIJY3nBfJK6jZj/ob4HQ7IREpEsuXPeYHMSF0PsC3eT6Bb/LkMF851jpScpO2S2ipHq17Pz3MqQIysUvbh76m0a5LbJFrF1IGUH8BjfMkHZDXHBM1dfnorKkjUVIk3eGpRQbImJRZ8IdyRWVHycbQsuXiPRFBQEDd0CbBu79y1BXQoAAAAAElFTkSuQmCC"
SAMPLE_UUIDv4 = "9b842b9dfad94f62a69b7d1e59557d27"

# rekognition
MAX_LABELS_PER_REQ = 5

# RDS Connection
DB_URL_ENV_VAR="CT_DB_URL"
DB_PORT_ENV_VAR="CT_DB_PORT"
DB_USERNAME_ENV_VAR="CT_DB_USERNAME"
DB_PASSWORD_ENV_VAR="CT_DB_PASSWORD"